### ISSUE TITLE
Disable IBL also disables transmission & translucency?

### ISSUE THREAD

**Issue by echadwick-wayfair** [ux3d/glTF-Sample-Viewer#114]
When I disable the Image Based lighting on a model with KHR_materials_transmission and KHR_materials_translucency, the transmission and translucency effects seem to be partially disabled. Maybe the render target is being affected by this GUI widget?

This bug is only observable with a model that contains a punctual light, just so you can see the materials. Here's a model with transmission and translucency and punctual lights: https://github.com/KhronosGroup/glTF-Sample-Models/tree/f56d1fb15a50cfc3b3ce80f86158152eec3df6cb/2.0/StainedGlassLamp/glTF-Translucency

When the IBL is disabled, the red and yellow gems show some transmission from the punctual lights, but they don't transmit any of the opaque surfaces behind them. The stained glass surface changes to black on the outside, except a small white effect which could be translucency.

![image](https://user-images.githubusercontent.com/40177036/106291491-b1b3ff00-6219-11eb-85b8-7367b978326b.png)

![image](https://user-images.githubusercontent.com/40177036/106291498-b5478600-6219-11eb-86f3-b17d573fe1b6.png)

**Comment by UX3D-becher** [comment]
resolved with  #125
