### ISSUE TITLE
Clearcoat debug channel doesn't take mask into account

### ISSUE THREAD

**Issue by emackey** [ux3d/glTF-Sample-Viewer#115]
Looking at the ToyCar model, and also the ClearcoatTest model, setting the Debug Channel to "Clearcoat" shows the whole thing clear-coated.

Areas like the interior of the ToyCar, and the 2nd row "Partial Coating" of the ClearcoatTest model, should have the coating excluded from part of the surface.

**Comment by UX3D-becher** [comment]
resolved with #122
