### ISSUE TITLE
Feature request: Right-click-drag to zoom?

### ISSUE THREAD

**Issue by echadwick-wayfair** [ux3d/glTF-Sample-Viewer#130]
Zoom seems to require the middle-mouse-wheel, which moves the camera in large increments, making it difficult to zoom precisely.

Could you add a new zoom control method? Hold down the right mouse button and move the mouse forward to zoom in, or backward to zoom out.

This method is available in the The Dassault Systèmes Enterprise PBR viewer. https://dassaultsystemes-technology.github.io/dspbr-pt/

**Comment by UX3D-becher** [comment]
the latest release version now supports right mouse button to zoom (see #136)
