### ISSUE TITLE
Camera export seems incorrect?

### ISSUE THREAD

**Issue by echadwick-wayfair** [ux3d/glTF-Sample-Viewer#133]
When I export camera code and add it to a glTF, Znear is missing, and the camera is not in the correct location.

1. Open the glTF Sample Viewer.
2. Drag-n-drop the SheenChair sample model (https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SheenChair/glTF/SheenChair.gltf)
3. Move the camera to a new location.
![capture](https://user-images.githubusercontent.com/40177036/107576024-9d2f1980-6bbe-11eb-8338-bc2176ba3aeb.png)

4. Advanced Controls: Capture Canvas: Download as PNG 
5. Current Camera Values: Copy to Clipboard.
6. Open the SheenChair.gltf in VSCode, with the glTF Tools extension.
7. Paste the camera code.
8. Format Document (Shift+Alt+F)
9. Examine the ToyCar.gltf to understand how cameras should be formatted in glTF (https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/ToyCar/glTF/ToyCar.gltf)
10. Move the new node data (from Clipboard) into the "nodes" section of the SheenChair, as the last node.
11. Increment the scenes/nodes count, adding another node # for the new camera.
12. Move the "camera" data (from Clipboard) into a new "cameras" section of the SheenChair, between "nodes" and "meshes"
13. Problem 1: There is a validation error. "Property 'znear' must be defined.
![2024F8~1](https://user-images.githubusercontent.com/40177036/107575361-db780900-6bbd-11eb-97c1-c777f2d17867.JPG)

14. Manually add "znear": 0.1 to the camera.
15. Save and Preview (Alt+G)
16. Enable Debug Mode (open the Babylon.js Inspector)
17. In the Nodes section, Expand All, and set the new camera0 as the main camera by clicking on its camera icon (immediately to the left of the eye icon). 
![2021-02-10 16_19_49-](https://user-images.githubusercontent.com/40177036/107575490-ea5ebb80-6bbd-11eb-8fcf-096386430a06.jpg)

18. Problem 2: model disappears. The camera seems to be in the incorrect position.
19. Set the default camera as the main camera again. 
![2021-02-10 16_20_37-](https://user-images.githubusercontent.com/40177036/107575510-f480ba00-6bbd-11eb-98d4-9d18850c38ce.jpg)

20. Turn on the gizmo for the new camera0 (the eye icon). Notice that the camera is not where it is supposed to be. 
![2021-02-10 16_22_26-glTF Preview  SheenChair gltf  - Visual Studio Code](https://user-images.githubusercontent.com/40177036/107575525-f9de0480-6bbd-11eb-8bf7-7e3d8f8d5ca7.jpg)

Confirmed by loading the edited gltf directly in the glTF Sample Viewer, and switching to camera 0. The camera only shows the skybox.

[SheenChair-with-Camera.zip](https://github.com/ux3d/glTF-Sample-Viewer/files/5961673/SheenChair-with-Camera.zip)

**Comment by UX3D-becher** [comment]
Thanks for testing and reporting this!  
We have fixed the camera transform in #139, now also the camera configuration is downloaded as a valid (albeit rather minimalistic) glTF file
