### ISSUE TITLE
wasm streaming compile failed

### ISSUE THREAD

**Issue by echadwick-wayfair** [ux3d/glTF-Sample-Viewer#140]
1. http://gltf.ux3d.io/
2. Ctrl+F5 to force refresh.
3. Error message appears at top:
![2021-02-15 10_39_45-glTF Sample Viewer](https://user-images.githubusercontent.com/40177036/107966899-784df400-6f7a-11eb-9276-d2c84e93390b.png)
then this message:
![2021-02-15 10_39_58-glTF Sample Viewer](https://user-images.githubusercontent.com/40177036/107966927-80a62f00-6f7a-11eb-9f64-57a846a72e0c.png)

Windows 10 Enterprise
Chrome Version 88.0.4324.150 (Official Build) (64-bit)

**Comment by UX3D-becher** [comment]
this was an issue with our webserver configuration, we fixed it on the site
