### ISSUE TITLE
Footprint spelling in Active Environment 

### ISSUE THREAD

**Issue by echadwick-wayfair** [ux3d/glTF-Sample-Viewer#141]
Hi there!

![image](https://user-images.githubusercontent.com/40177036/107971075-fe206e00-6f7f-11eb-8215-25f914292519.png)

I think it should be Footprint instead of Foodprint.

The original source IBL is here:
http://www.hdrlabs.com/sibl/archive.html

Thank you!

**Comment by UX3D-becher** [comment]
thanks for the report, it is fixed with commit 36ad2cd6c860fc6e21c42ed3a2aded7827bf02d9
