### ISSUE TITLE
Issue with alpha transparency and transmission

### ISSUE THREAD

**Issue by thomasdideriksen** [ux3d/glTF-Sample-Viewer#144]
Materials using transmission are _not_ rendered when appearing behind materials using alpha transparency.
![image](https://user-images.githubusercontent.com/9837134/108267921-ae2cdd00-7120-11eb-829d-e5b4c3ec1b50.png)

The same model renders as expected in Babylon.js:
![image](https://user-images.githubusercontent.com/9837134/108268058-e3d1c600-7120-11eb-9533-b841b1d54330.png)

I've attached the sample model here, for reference:
[transmission_alpha.zip](https://github.com/ux3d/glTF-Sample-Viewer/files/5998612/transmission_alpha.zip)

If this is an intentional/known limitation, please disregard.

**Comment by UX3D-becher** [comment]
fixed with #146
