### ISSUE TITLE
Transmission rendering issue

### ISSUE THREAD

**Issue by UX3D-nopper** [ux3d/glTF-Sample-Viewer#82]
1. Download the StainedGlassLamp GLB from https://github.com/KhronosGroup/glTF-Sample-Models/pull/288 (https://github.com/KhronosGroup/glTF-Sample-Models/blob/a0b090da192dde2a1c3a82dd2e3720c912631b0a/2.0/StainedGlassLamp/glTF-Binary/StainedGlassLamp.glb)

2. Drag-and-drop into http://gltf.ux3d.io/

3. Rotate the camera around the model.

Result: Notice at some angles the stained glass colors are replaced with the IBL colors.

Before rotating the camera (this looks correct):
![image](https://user-images.githubusercontent.com/27856744/105287058-bb08f000-5bb7-11eb-88e3-f6bfa1bc1ee7.png)

After rotating the camera (this looks incorrect, the baseColor is not affecting the transmission color):
![image-bug](https://user-images.githubusercontent.com/27856744/105287096-ccea9300-5bb7-11eb-977e-1118fe621e3a.png)

**Comment by UX3D-becher** [comment]
has been fixed with the beta release #117
